# Generated by Django 4.2.5 on 2023-11-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_name', models.CharField(max_length=40, verbose_name='название фильма')),
                ('film_country', models.CharField(max_length=40, verbose_name='страна')),
                ('film_year', models.IntegerField(verbose_name='год')),
            ],
        ),
    ]
